import { useEffect, useRef, useState } from 'react'
import { X, Download, FileText } from 'lucide-react'
import { motion, AnimatePresence } from 'framer-motion'
import { generateReportPdfFromHtml } from '../../utils/htmlReportToPdf.js'
import { aiRadiantRead, cxWhyThisMatters } from '../../data/reportEditorial.js'

/**
 * HTMLReportViewer — renders the full branded HTML report in a full-screen modal.
 * Also provides a "Download HTML" button and a backend email path.
 *
 * The report HTML is generated by buildAiReportHtml() or buildCxReportHtml(),
 * both defined at the bottom of this file.
 *
 * Props:
 *   open         boolean
 *   onClose      () => void
 *   kind         'ai' | 'cx'
 *   profile      { fullName, workEmail, companyName, sector, orgSize, department, role }
 *   result       scored result object (from scoreAssessment / scoreCx)
 *   sentTo       string — email address it was sent to ('' if not yet sent)
 */
export default function HTMLReportViewer({ open, onClose, kind, profile, result, sentTo = '' }) {
  const iframeRef = useRef(null)
  const [pdfBusy, setPdfBusy] = useState(false)

  const html = kind === 'ai' ? buildAiReportHtml(profile, result) : buildCxReportHtml(profile, result)

  // Inject HTML into iframe when open
  useEffect(() => {
    if (open && iframeRef.current) {
      const doc = iframeRef.current.contentDocument
      doc.open()
      doc.write(html)
      doc.close()
    }
  }, [open, html])

  // Close on Escape
  useEffect(() => {
    const fn = (e) => { if (e.key === 'Escape') onClose() }
    if (open) document.addEventListener('keydown', fn)
    return () => document.removeEventListener('keydown', fn)
  }, [open, onClose])

  // Primary download: convert the exact HTML shown here into a PDF so the file
  // matches the on-screen report 1:1.
  const downloadPdf = async () => {
    setPdfBusy(true)
    try {
      await generateReportPdfFromHtml({ kind, profile, result })
    } finally {
      setPdfBusy(false)
    }
  }

  const downloadHtml = () => {
    const blob = new Blob([html], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `radiant-${kind}-assessment-report-${(profile?.fullName || 'report').toLowerCase().replace(/\s+/g, '-')}.html`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          className="fixed inset-0 z-[100] flex flex-col"
          initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
          transition={{ duration: 0.2 }}
        >
          {/* Backdrop */}
          <div className="absolute inset-0 bg-black/80 backdrop-blur-sm" onClick={onClose} />

          {/* Panel */}
          <motion.div
            className="relative z-10 flex flex-col w-full h-full"
            initial={{ y: 40, opacity: 0 }} animate={{ y: 0, opacity: 1 }} exit={{ y: 20, opacity: 0 }}
            transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}
          >
            {/* Top bar */}
            <div className="flex items-center justify-between px-5 py-3 flex-shrink-0"
              style={{ background: '#010F1E', borderBottom: '1px solid rgba(255,255,255,0.08)' }}>
              <div className="flex items-center gap-3">
                <span className="font-display font-bold text-white text-sm">
                  {kind === 'ai' ? 'AI Adoption Report' : 'CX Maturity Report'}
                </span>
                {sentTo && (
                  <span className="text-[10px] font-medium px-2 py-0.5 rounded-full"
                    style={{ background: 'rgba(145,196,107,0.12)', color: '#91C46B', border: '1px solid rgba(145,196,107,0.25)' }}>
                    Emailed to {sentTo}
                  </span>
                )}
              </div>
              <div className="flex items-center gap-2">
                <button onClick={downloadPdf} disabled={pdfBusy}
                  className="flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-lg transition-colors disabled:opacity-50"
                  style={{ background: 'rgba(145,196,107,0.12)', color: '#91C46B', border: '1px solid rgba(145,196,107,0.25)' }}>
                  <Download size={13} /> {pdfBusy ? 'Preparing PDF…' : 'Download PDF'}
                </button>
                <button onClick={downloadHtml}
                  className="flex items-center gap-1.5 text-text-muted hover:text-white transition-colors text-xs font-medium px-3 py-1.5 rounded-lg hover:bg-white/[0.06]">
                  <FileText size={13} /> HTML
                </button>
                <button onClick={onClose}
                  className="flex items-center justify-center w-8 h-8 rounded-lg text-text-muted hover:text-white hover:bg-white/[0.06] transition-colors">
                  <X size={16} />
                </button>
              </div>
            </div>

            {/* iframe */}
            <iframe
              ref={iframeRef}
              title="Assessment Report"
              className="flex-1 w-full border-0"
              style={{ background: '#fff' }}
              sandbox="allow-same-origin"
            />
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  )
}

// ── HTML Report Builders ─────────────────────────────────────────────────────

function radiantBranding() {
  return `
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700;900&family=Inter:wght@400;500;600&display=swap');
      * { box-sizing: border-box; margin: 0; padding: 0; }
      body { font-family: 'Inter', sans-serif; background: #f8fafc; color: #1e293b; line-height: 1.6; }
      .report { max-width: 800px; margin: 0 auto; padding: 0; }

      /* Header */
      .header { background: #010F1E; padding: 40px 48px 32px; }
      .header-top { display: flex; align-items: center; justify-content: space-between; margin-bottom: 32px; }
      .logo { font-family: 'Poppins', sans-serif; font-weight: 900; font-size: 18px; color: #91C46B; letter-spacing: -0.02em; }
      .logo span { color: #fff; }
      .report-date { font-size: 11px; color: rgba(255,255,255,0.35); font-weight: 500; }
      .header-headline { font-family: 'Poppins', sans-serif; font-weight: 900; font-size: clamp(28px, 5vw, 40px); color: #fff; line-height: 1.05; letter-spacing: -0.02em; }
      .header-headline .accent { color: #91C46B; }
      .header-meta { display: flex; flex-wrap: wrap; gap: 12px; margin-top: 20px; }
      .meta-chip { font-size: 11px; font-weight: 600; padding: 4px 12px; border-radius: 100px; background: rgba(255,255,255,0.07); color: rgba(255,255,255,0.55); border: 1px solid rgba(255,255,255,0.1); }

      /* Sections */
      .section { padding: 36px 48px; border-bottom: 1px solid #e2e8f0; background: #fff; }
      .section:last-child { border-bottom: none; }
      .section-alt { background: #f8fafc; }
      .kicker { font-family: 'Poppins', sans-serif; font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.12em; color: #91C46B; margin-bottom: 8px; display: block; }
      .section-title { font-family: 'Poppins', sans-serif; font-weight: 900; font-size: 22px; color: #0f172a; letter-spacing: -0.015em; margin-bottom: 6px; line-height: 1.2; }
      .section-body { font-size: 14px; color: #475569; line-height: 1.75; }

      /* Stage reveal */
      .stage-block { background: #010F1E; border-radius: 16px; padding: 32px; margin-top: 20px; }
      .stage-label { font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; color: rgba(255,255,255,0.4); margin-bottom: 8px; }
      .stage-name { font-family: 'Poppins', sans-serif; font-weight: 900; font-size: 36px; color: #91C46B; letter-spacing: -0.02em; }
      .stage-tagline { font-size: 14px; color: rgba(255,255,255,0.6); font-weight: 600; margin: 8px 0 16px; }
      .pip-row { display: flex; gap: 6px; margin-bottom: 20px; }
      .pip { height: 8px; flex: 1; border-radius: 100px; }
      .pip-filled { background: #91C46B; }
      .pip-empty { background: rgba(255,255,255,0.08); }
      .stage-desc { font-size: 14px; color: rgba(255,255,255,0.65); line-height: 1.8; }

      /* Score bars */
      .score-row { margin-bottom: 20px; }
      .score-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px; }
      .score-label { font-family: 'Poppins', sans-serif; font-weight: 600; font-size: 13px; color: #1e293b; }
      .score-value { font-size: 12px; font-weight: 700; }
      .bar-track { height: 10px; background: #e2e8f0; border-radius: 100px; overflow: hidden; }
      .bar-fill { height: 100%; border-radius: 100px; }

      /* Findings */
      .findings-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; margin-top: 20px; }
      @media (max-width: 600px) { .findings-grid { grid-template-columns: 1fr; } }
      .finding-group-label { font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; margin-bottom: 12px; }
      .finding { display: flex; gap: 12px; margin-bottom: 16px; }
      .finding-icon { width: 18px; height: 18px; flex-shrink: 0; margin-top: 1px; }
      .finding-title { font-family: 'Poppins', sans-serif; font-weight: 700; font-size: 13px; color: #0f172a; margin-bottom: 4px; }
      .finding-section { font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; color: #94a3b8; margin-bottom: 4px; }
      .finding-body { font-size: 12px; color: #64748b; line-height: 1.65; }

      /* Next step */
      .next-step-block { background: linear-gradient(135deg, #010F1E 0%, #051A30 100%); border-radius: 16px; padding: 28px 32px; margin-top: 20px; border-left: 3px solid #91C46B; }
      .next-step-section { font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; color: #91C46B; margin-bottom: 6px; }
      .next-step-text { font-size: 14px; color: rgba(255,255,255,0.75); line-height: 1.75; }

      /* CTA */
      .cta-block { background: #010F1E; padding: 36px 48px; text-align: center; }
      .cta-title { font-family: 'Poppins', sans-serif; font-weight: 900; font-size: 24px; color: #fff; margin-bottom: 12px; letter-spacing: -0.015em; }
      .cta-body { font-size: 14px; color: rgba(255,255,255,0.55); margin-bottom: 28px; line-height: 1.7; }
      .cta-btn { display: inline-block; background: #91C46B; color: #010F1E; font-family: 'Poppins', sans-serif; font-weight: 700; font-size: 14px; padding: 14px 32px; border-radius: 100px; text-decoration: none; }
      .cta-email { font-size: 12px; color: rgba(255,255,255,0.35); margin-top: 16px; }

      /* Radiant read */
      .radiant-read { background: rgba(145,196,107,0.06); border: 1px solid rgba(145,196,107,0.15); border-radius: 12px; padding: 20px 24px; margin-top: 20px; }
      .radiant-read-label { font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; color: #91C46B; margin-bottom: 8px; }
      .radiant-read-text { font-size: 13px; color: #334155; line-height: 1.75; }

      @media print {
        body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
        .header { -webkit-print-color-adjust: exact; }
      }
    </style>`
}

// ── AI Assessment HTML Report ────────────────────────────────────────────────

export function buildAiReportHtml(profile, result) {
  if (!result?.stage) return '<html><body>Report data unavailable.</body></html>'

  const { stage, sectionAverages = {}, findings = {}, nextStep } = result
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  const scoreBarColor = (score) => {
    if (score < 2) return '#EF4444'
    if (score < 3) return '#F59E0B'
    if (score < 4) return '#06B6D4'
    return '#22C55E'
  }

  const scoreLabel = (score) => {
    if (score < 2) return 'Needs attention'
    if (score < 3) return 'Below target'
    if (score < 4) return 'On track'
    return 'Strong'
  }

  const sections = [
    { key: 'Strategy', label: 'Strategy & Leadership' },
    { key: 'Data', label: 'Data & Technology' },
    { key: 'People', label: 'People & Governance' },
    { key: 'Adoption', label: 'Adoption & Value' },
  ]

  const pips = Array.from({ length: 6 }, (_, i) =>
    `<div class="pip ${i < stage.index ? 'pip-filled' : 'pip-empty'}"></div>`).join('')

  // Header meta pills — built from whatever profile data exists, empties dropped
  // so we never render blank chips. Always carries at least role track + stage.
  const roleLabel = { exec: 'Executive', tech: 'Technical Lead', biz: 'Business Lead', consultant: 'Consultant' }[profile?.role]
  const metaChips = [
    profile?.fullName,
    profile?.companyName,
    profile?.sector,
    profile?.orgSize ? `${profile.orgSize} employees` : null,
    profile?.department,
    roleLabel ? `${roleLabel} Track` : null,
    `Stage ${stage.index} of 6`,
    now,
  ].filter(Boolean)
  const metaChipsHtml = metaChips.map(c => `<span class="meta-chip">${c}</span>`).join('')

  const strengthsHtml = (findings.strengths || []).map(s => `
    <div class="finding">
      <svg class="finding-icon" viewBox="0 0 20 20" fill="none"><circle cx="10" cy="10" r="9" stroke="#22C55E" stroke-width="1.5"/><path d="M6.5 10l2.5 2.5 4.5-5" stroke="#22C55E" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>
      <div>
        <div class="finding-section">${s.section}</div>
        <div class="finding-title">${s.title}</div>
        <div class="finding-body">${s.body}</div>
      </div>
    </div>`).join('')

  const gapsHtml = (findings.gaps || []).map(g => `
    <div class="finding">
      <svg class="finding-icon" viewBox="0 0 20 20" fill="none"><path d="M10 3L18 17H2L10 3z" stroke="#F59E0B" stroke-width="1.5" stroke-linejoin="round"/><path d="M10 9v4M10 14.5v.5" stroke="#F59E0B" stroke-width="1.5" stroke-linecap="round"/></svg>
      <div>
        <div class="finding-section">${g.section}</div>
        <div class="finding-title">${g.title}</div>
        <div class="finding-body">${g.body}</div>
      </div>
    </div>`).join('')

  const scoreBarsHtml = sections.map(s => {
    const score = sectionAverages[s.key] || 0
    const pct = (score / 5) * 100
    const color = scoreBarColor(score)
    const label = scoreLabel(score)
    return `
      <div class="score-row">
        <div class="score-header">
          <span class="score-label">${s.label}</span>
          <span class="score-value" style="color:${color}">${score ? score.toFixed(1) : '—'} · ${label}</span>
        </div>
        <div class="bar-track">
          <div class="bar-fill" style="width:${pct}%; background:${color};"></div>
        </div>
      </div>`
  }).join('')

  const nextStepHtml = nextStep ? `
    <div class="next-step-block">
      <div class="next-step-section">Priority action — ${nextStep.section}</div>
      <div class="next-step-text">${nextStep.text}</div>
    </div>` : ''

  const findingsSection = (strengthsHtml || gapsHtml) ? `
    <div class="section">
      <span class="kicker">What We See</span>
      <div class="section-title">Your Strengths &amp; Gaps</div>
      <div class="findings-grid">
        ${strengthsHtml ? `<div><div class="finding-group-label" style="color:#22C55E">Strengths</div>${strengthsHtml}</div>` : ''}
        ${gapsHtml ? `<div><div class="finding-group-label" style="color:#F59E0B">Gaps to Close</div>${gapsHtml}</div>` : ''}
      </div>
    </div>` : ''

  // Radiant's read — stage-specific editorial commentary (shared source)
  const radiantRead = aiRadiantRead

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>AI Adoption Report — ${profile?.fullName || 'Assessment'}</title>
  ${radiantBranding()}
</head>
<body>
<div class="report">
  <!-- Header -->
  <div class="header">
    <div class="header-top">
      <div class="logo"><span>\\\\</span>RADIANT AI</div>
      <div class="report-date">${now}</div>
    </div>
    <div class="header-headline">
      AI Adoption Report<br/>
      <span class="accent">Stage ${stage.index} — ${stage.name}</span>
    </div>
    <div class="header-meta">
      ${metaChipsHtml}
    </div>
  </div>

  <!-- Stage Reveal -->
  <div class="section">
    <span class="kicker">Your AI Maturity</span>
    <div class="stage-block">
      <div class="stage-label">Your Stage</div>
      <div class="stage-name">Stage ${stage.index} — ${stage.name}</div>
      <div class="stage-tagline">${stage.tagline || ''}</div>
      <div class="pip-row">${pips}</div>
      <div class="stage-desc">${stage.description || ''}</div>
    </div>
  </div>

  <!-- Score Breakdown -->
  <div class="section section-alt">
    <span class="kicker">Scores by Dimension</span>
    <div class="section-title">How You Scored</div>
    <div style="margin-top:20px">${scoreBarsHtml}</div>
  </div>

  <!-- Findings -->
  ${findingsSection}

  <!-- Next Step -->
  ${nextStep ? `
  <div class="section">
    <span class="kicker">Recommended Next Step</span>
    <div class="section-title">Where to Focus First</div>
    <div class="section-body" style="margin-top:8px">The lowest-scoring dimension points to the highest-leverage action. Fixing this first removes the constraint that's limiting everything else.</div>
    ${nextStepHtml}
  </div>` : ''}

  <!-- Radiant's Read -->
  <div class="section section-alt">
    <span class="kicker">Radiant's Read</span>
    <div class="section-title">What This Means for You</div>
    <div class="radiant-read">
      <div class="radiant-read-label">Our perspective on Stage ${stage.index} organizations</div>
      <div class="radiant-read-text">${radiantRead[stage.index] || radiantRead[6]}</div>
    </div>
  </div>

  <!-- CTA -->
  <div class="cta-block">
    <div class="cta-title">Ready to move to Stage ${Math.min(stage.index + 1, 6)}?</div>
    <div class="cta-body">Radiant has helped enterprises across 14+ industries move through every stage of AI maturity. A 30-minute conversation is enough to map exactly where to start.</div>
    <a href="https://radiant.digital/contact" class="cta-btn">Schedule 30 Minutes with Radiant</a>
    <div class="cta-email">Or email us at hello@radiant.digital</div>
  </div>
</div>
</body>
</html>`
}

// ── CX Assessment HTML Report ────────────────────────────────────────────────

export function buildCxReportHtml(profile, result) {
  if (!result?.overallLevel) return '<html><body>Report data unavailable.</body></html>'
  const { dimensions = [], overallLevel, overallKey } = result
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  const levelColor = { Foundational: '#F0974E', Developing: '#596AE0', Advanced: '#91C46B' }
  const color = levelColor[overallLevel] || '#91C46B'
  const levelIndex = { Foundational: 1, Developing: 2, Advanced: 3 }[overallLevel] || 1
  const pips = Array.from({ length: 3 }, (_, i) =>
    `<div class="pip ${i < levelIndex ? 'pip-filled' : 'pip-empty'}" style="${i < levelIndex ? `background:${color}` : ''}"></div>`).join('')

  // Header meta pills — empties dropped so no blank chips ever render
  const metaChips = [
    profile?.fullName,
    profile?.companyName,
    profile?.sector,
    profile?.orgSize ? `${profile.orgSize} employees` : null,
    profile?.department,
    `${overallLevel} maturity`,
    now,
  ].filter(Boolean)
  const metaChipsHtml = metaChips.map(c => `<span class="meta-chip">${c}</span>`).join('')

  const dimsHtml = dimensions.map(d => `
    <div style="padding:20px 0; border-bottom:1px solid #e2e8f0;">
      <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:8px;">
        <span style="font-family:Poppins,sans-serif;font-weight:700;font-size:14px;color:#0f172a">${d.label}</span>
        <span style="font-size:11px;font-weight:700;padding:3px 10px;border-radius:100px;background:${levelColor[d.level]}18;color:${levelColor[d.level]};border:1px solid ${levelColor[d.level]}30">${d.level}</span>
      </div>
      <p style="font-size:13px;color:#64748b;line-height:1.7">${d.blurb || ''}</p>
    </div>`).join('')

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>CX Maturity Report — ${profile?.fullName || 'Assessment'}</title>
  ${radiantBranding()}
  <style>.pip-filled { background: ${color} !important; }</style>
</head>
<body>
<div class="report">
  <div class="header">
    <div class="header-top">
      <div class="logo"><span>\\\\</span>RADIANT AI</div>
      <div class="report-date">${now}</div>
    </div>
    <div class="header-headline">
      CX Maturity Report<br/>
      <span style="color:${color}">${overallLevel}</span>
    </div>
    <div class="header-meta">
      ${metaChipsHtml}
    </div>
  </div>

  <div class="section">
    <span class="kicker">Your CX Maturity Level</span>
    <div class="stage-block">
      <div class="stage-label">Overall Maturity</div>
      <div class="stage-name" style="color:${color}">${overallLevel}</div>
      <div class="pip-row">${pips}</div>
    </div>
  </div>

  <div class="section section-alt">
    <span class="kicker">Dimension Breakdown</span>
    <div class="section-title">How You Scored Across Three Dimensions</div>
    <div style="margin-top:4px">${dimsHtml}</div>
  </div>

  <div class="section">
    <span class="kicker">Recommended Solution</span>
    <div class="section-title">Experience AI by Radiant</div>
    <div class="section-body" style="margin-top:12px">To help you progress to the next maturity level, Radiant recommends Experience AI — our qualitative + quantitative insight engine. It helps you reveal root causes driving customer behavior, turn interviews, surveys, and public data into structured CX insights, build early journey maps and opportunity areas, and establish repeatable insight-to-action workflows.</div>
    <div class="radiant-read" style="margin-top:20px">
      <div class="radiant-read-label">Why this matters at the ${overallLevel} level</div>
      <div class="radiant-read-text">${cxWhyThisMatters(overallKey)}</div>
    </div>
  </div>

  <div class="cta-block">
    <div class="cta-title">Let's build your CX roadmap.</div>
    <div class="cta-body">Radiant's CX practice has helped enterprises across financial services, healthcare, and technology improve CSAT by 20%+ within 90 days. We'd like to show you what that looks like for your organization.</div>
    <a href="https://radiant.digital/contact" class="cta-btn">Schedule a CX Strategy Session</a>
    <div class="cta-email">hello@radiant.digital</div>
  </div>
</div>
</body>
</html>`
}
